// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Share.Common.Workflow.Api.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\applications\{applicationId}\complete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete.CompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/applications/{applicationId}/complete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete.CompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/applications/{applicationId}/complete", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 500 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 502 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse?> PostAsync(global::Share.Common.Workflow.Api.Client.Models.CompleteApplicationWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse> PostAsync(global::Share.Common.Workflow.Api.Client.Models.CompleteApplicationWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "404", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "500", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "502", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse>(requestInfo, global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Share.Common.Workflow.Api.Client.Models.CompleteApplicationWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Share.Common.Workflow.Api.Client.Models.CompleteApplicationWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete.CompleteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete.CompleteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.Complete.CompleteRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
