// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Share.Common.Workflow.Api.Client.Workflows.Applications;
using Share.Common.Workflow.Api.Client.Workflows.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Share.Common.Workflow.Api.Client.Workflows
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applications property</summary>
        public global::Share.Common.Workflow.Api.Client.Workflows.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Share.Common.Workflow.Api.Client.Workflows.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Share.Common.Workflow.Api.Client.workflows.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder"/></returns>
        public global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("workflowType", position);
                return new global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
