//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Common.Workflow.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkflowValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Common.Workflow.Core.Resources.WorkflowValidation", typeof(WorkflowValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active workflow was not found for the application..
        /// </summary>
        public static string ActiveWorkflowNotExists {
            get {
                return ResourceManager.GetString("ActiveWorkflowNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow is in progress for this applicationId.
        /// </summary>
        public static string ApplicationWorkflowExists {
            get {
                return ResourceManager.GetString("ApplicationWorkflowExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a level {0} for specified workflow.
        /// </summary>
        public static string AppWorkflowLevelNotExists {
            get {
                return ResourceManager.GetString("AppWorkflowLevelNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a sage {0} for the application workflow..
        /// </summary>
        public static string AppWorkflowLevelStageNotExists {
            get {
                return ResourceManager.GetString("AppWorkflowLevelStageNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete following actions to complete the stage {0}.
        /// </summary>
        public static string AppWorkflowPendingAction {
            get {
                return ResourceManager.GetString("AppWorkflowPendingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending stage actions and active levels. Please close those before marking as complete..
        /// </summary>
        public static string AppWorkflowPendingLevels {
            get {
                return ResourceManager.GetString("AppWorkflowPendingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The privilege for the workflow decision doesn&apos;t exist..
        /// </summary>
        public static string AppWorkflowStagePrivilegeNotExist {
            get {
                return ResourceManager.GetString("AppWorkflowStagePrivilegeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow type is not fond in the system.
        /// </summary>
        public static string WorkflowNotFoundForType {
            get {
                return ResourceManager.GetString("WorkflowNotFoundForType", resourceCulture);
            }
        }
    }
}
