// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share.Common.Workflow.Core.Infrastructure.Services;

#nullable disable

namespace Share.Common.Workflow.EFCoreMigrations.Dev.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20250319104852_AddWorkflowType_Role")]
    partial class AddWorkflowType_Role
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflow", b =>
                {
                    b.Property<Guid>("AppWorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentStageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)");

                    b.HasKey("AppWorkflowId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ParentStageId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("AppWorkflows", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevel", b =>
                {
                    b.Property<Guid>("AppWorkflowLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.HasKey("AppWorkflowLevelId");

                    b.HasIndex("AppWorkflowId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("WorkflowLevelId");

                    b.ToTable("AppWorkflowLevels", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", b =>
                {
                    b.Property<Guid>("AppWorkflowLevelStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("char(36)");

                    b.HasKey("AppWorkflowLevelStageId");

                    b.HasIndex("AppWorkflowLevelId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("StageId");

                    b.ToTable("AppWorkflowLevelStages", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStageAction", b =>
                {
                    b.Property<Guid>("AppWorkflowLevelStageActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppOfficerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionMadeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.HasKey("AppWorkflowLevelStageActionId");

                    b.HasIndex("AppOfficerId");

                    b.HasIndex("AppWorkflowLevelStageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("AppWorkflowLevelStageActions", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStagePrivilegeAction", b =>
                {
                    b.Property<Guid>("AppWorkflowLevelStagePrivilegeActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationWorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("AppWorkflowLevelStagePrivilegeActionId");

                    b.HasIndex("ApplicationWorkflowLevelStageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("AppWorkflowLevelStagePrivilegeActions", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.ApplicationOfficer", b =>
                {
                    b.Property<Guid>("ApplicationOfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("char(36)");

                    b.HasKey("ApplicationOfficerId");

                    b.HasIndex("AppWorkflowId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("OfficerId");

                    b.ToTable("ApplicationOfficers", "Application");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflow", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentStageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("AppWorkflows_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAppWorkflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevel", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("AppWorkflowLevels_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAppWorkflowLevel");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStage", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("AppWorkflowLevelStages_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAppWorkflowLevelStage");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStageAction", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppOfficerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelStageActionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionMadeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("AppWorkflowLevelStageActions_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAppWorkflowLevelStageAction");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStagePrivilegeAction", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowLevelStagePrivilegeActionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationWorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("AppWorkflowLevelStagePrivilegeActions_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAppWorkflowLevelStagePrivilegeAction");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditApplicationOfficer", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppWorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationOfficerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("ApplicationOfficers_Audit", "Application");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditApplicationOfficer");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditCompany", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UenNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("Companies_Audit", "Companies");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditCompany");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMedicsAccountRole", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicsAccountRoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicsRoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("MedicsAccountRoles_Audit", "Auth");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditMedicsAccountRole");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMopProfile", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MopProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("MopProfiles_Audit", "Auth");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditMopProfile");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMopProfileCompany", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MopProfileCompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MopProfileId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("MopProfileCompanies_Audit", "Companies");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditMopProfileCompany");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditOfficerProfile", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("OfficerProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SoeId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("OfficerProfiles_Audit", "Auth");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditOfficerProfile");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflow", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("Workflows_Audit", "Workflow");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditWorkflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevel", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkflowRole")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("WorkflowLevels_Audit", "Workflow");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditWorkflowLevel");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevelStage", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("StageIdentifier")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowLevelStageId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("WorkflowLevelStages_Audit", "Workflow");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditWorkflowLevelStage");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevelStagePrivilege", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("PrivilegeRequirementType")
                        .HasColumnType("int");

                    b.Property<int>("PrivilegeType")
                        .HasColumnType("int");

                    b.Property<Guid>("StageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowLevelStagePrivilegeId")
                        .HasColumnType("char(36)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("WorkflowLevelStagePrivileges_Audit", "Workflow");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditWorkflowLevelStagePrivilege");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UenNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("UenNumber")
                        .IsUnique();

                    b.ToTable("Companies", "Companies");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MedicsAccountRole", b =>
                {
                    b.Property<Guid>("MedicsAccountRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicsRoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("MedicsAccountRoleId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("MedicsRoleId");

                    b.ToTable("MedicsAccountRoles", "Auth");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MedicsRole", b =>
                {
                    b.Property<Guid>("MedicsRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowType")
                        .HasColumnType("int");

                    b.HasKey("MedicsRoleId");

                    b.ToTable("MedicsRoles", "Auth");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MopProfile", b =>
                {
                    b.Property<Guid>("MopProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("MopProfileId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("MopProfiles", "Auth");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MopProfileCompany", b =>
                {
                    b.Property<Guid>("MopProfileCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MopProfileId")
                        .HasColumnType("char(36)");

                    b.HasKey("MopProfileCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("MopProfileId");

                    b.ToTable("MopProfileCompanies", "Companies");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.OfficerProfile", b =>
                {
                    b.Property<Guid>("OfficerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SoeId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OfficerProfileId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("OfficerProfiles", "Auth");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("int");

                    b.HasKey("WorkflowId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Workflows", "Workflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevel", b =>
                {
                    b.Property<Guid>("WorkflowLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkflowRole")
                        .HasColumnType("int");

                    b.HasKey("WorkflowLevelId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowLevels", "Workflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevelStage", b =>
                {
                    b.Property<Guid>("WorkflowLevelStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("StageIdentifier")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowLevelId")
                        .HasColumnType("char(36)");

                    b.HasKey("WorkflowLevelStageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("WorkflowLevelId");

                    b.ToTable("WorkflowLevelStages", "Workflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevelStagePrivilege", b =>
                {
                    b.Property<Guid>("WorkflowLevelStagePrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("PrivilegeRequirementType")
                        .HasColumnType("int");

                    b.Property<int>("PrivilegeType")
                        .HasColumnType("int");

                    b.Property<Guid>("StageId")
                        .HasColumnType("char(36)");

                    b.HasKey("WorkflowLevelStagePrivilegeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("StageId");

                    b.ToTable("WorkflowLevelStagePrivileges", "Workflow");
                });

            modelBuilder.Entity("Share.Lib.Bootstrap.Api.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Accounts", "Auth");
                });

            modelBuilder.Entity("Share.Lib.Bootstrap.Api.Core.Entities.AuditAccount", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("AuditActionById")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionById");

                    b.ToTable("Accounts_Audit", "Auth");

                    b.HasDiscriminator().IsComplete(false).HasValue("AuditAccount");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflow", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", "ParentStage")
                        .WithMany("Workflows")
                        .HasForeignKey("ParentStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.Workflow", "Workflow")
                        .WithMany("Applications")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ParentStage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevel", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflow", "AppWorkflow")
                        .WithMany("Levels")
                        .HasForeignKey("AppWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.WorkflowLevel", "WorkflowLevel")
                        .WithMany("Applications")
                        .HasForeignKey("WorkflowLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppWorkflow");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("WorkflowLevel");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflowLevel", "AppWorkflowLevel")
                        .WithMany("Stages")
                        .HasForeignKey("AppWorkflowLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.WorkflowLevelStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppWorkflowLevel");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStageAction", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.ApplicationOfficer", "AppOfficer")
                        .WithMany("StageActions")
                        .HasForeignKey("AppOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", "AppWorkflowLevelStage")
                        .WithMany("Actions")
                        .HasForeignKey("AppWorkflowLevelStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppOfficer");

                    b.Navigation("AppWorkflowLevelStage");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStagePrivilegeAction", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", "ApplicationWorkflowLevelStage")
                        .WithMany("PrivilegeActions")
                        .HasForeignKey("ApplicationWorkflowLevelStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationWorkflowLevelStage");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.ApplicationOfficer", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.AppWorkflow", "AppWorkflow")
                        .WithMany()
                        .HasForeignKey("AppWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppWorkflow");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflow", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevel", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStage", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStageAction", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditAppWorkflowLevelStagePrivilegeAction", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditApplicationOfficer", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditCompany", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMedicsAccountRole", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMopProfile", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditMopProfileCompany", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditOfficerProfile", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflow", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevel", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevelStage", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AuditWorkflowLevelStagePrivilege", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Company", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MedicsAccountRole", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("Share.Common.Workflow.Core.Entities.MedicsRole", "MedicsRole")
                        .WithMany()
                        .HasForeignKey("MedicsRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("MedicsRole");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MopProfile", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MopProfileCompany", b =>
                {
                    b.HasOne("Share.Common.Workflow.Core.Entities.Company", "Company")
                        .WithMany("MopProfiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.MopProfile", "MopProfile")
                        .WithMany("Companies")
                        .HasForeignKey("MopProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("MopProfile");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.OfficerProfile", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Workflow", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevel", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.Workflow", "Workflow")
                        .WithMany("Levels")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevelStage", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.WorkflowLevel", "WorkflowLevel")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("WorkflowLevel");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevelStagePrivilege", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Share.Common.Workflow.Core.Entities.WorkflowLevelStage", "Stage")
                        .WithMany("Privileges")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Share.Lib.Bootstrap.Api.Core.Entities.Account", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Share.Lib.Bootstrap.Api.Core.Entities.AuditAccount", b =>
                {
                    b.HasOne("Share.Lib.Bootstrap.Api.Core.Entities.Account", "AuditActionBy")
                        .WithMany()
                        .HasForeignKey("AuditActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionBy");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflow", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevel", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.AppWorkflowLevelStage", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("PrivilegeActions");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.ApplicationOfficer", b =>
                {
                    b.Navigation("StageActions");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Company", b =>
                {
                    b.Navigation("MopProfiles");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.MopProfile", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.Workflow", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevel", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Share.Common.Workflow.Core.Entities.WorkflowLevelStage", b =>
                {
                    b.Navigation("Privileges");
                });
#pragma warning restore 612, 618
        }
    }
}
