namespace EFQueryLens.Core.Contracts;

public record TranslationRequest
{
    /// <summary>
    /// Request payload contract version for LSP -> daemon wire compatibility.
    /// Daemon rejects requests that do not match <see cref="TranslationRequestContract.Version"/>.
    /// </summary>
    public int RequestContractVersion { get; init; } = TranslationRequestContract.Version;

    /// <summary>
    /// LINQ expression as C# source text.
    /// Example: "db.Orders.Where(o => o.UserId == 5).Include(o => o.Items)"
    /// </summary>
    public required string Expression { get; init; }

    /// <summary>
    /// The source-authored expression as seen in the editor before LSP rewrites.
    /// Optional: falls back to <see cref="Expression"/> when omitted.
    /// </summary>
    public string? OriginalExpression { get; init; }

    /// <summary>
    /// The LSP-authoritative rewritten expression to execute.
    /// Optional: falls back to <see cref="Expression"/> when omitted.
    /// </summary>
    public string? RewrittenExpression { get; init; }

    /// <summary>
    /// Names of LSP rewrite passes that were applied (for diagnostics/telemetry).
    /// </summary>
    public IReadOnlyList<string> RewriteFlags { get; init; } = [];

    public required string AssemblyPath { get; init; }

    /// <summary>null = auto-discover the first DbContext found in the assembly.</summary>
    public string? DbContextTypeName { get; init; }

    /// <summary>Name of the DbContext variable in the script globals. Defaults to "db".</summary>
    public string ContextVariableName { get; init; } = "db";

    /// <summary>
    /// Extra namespace imports used when compiling the expression in Roslyn script.
    /// This is mainly populated by the LSP host from source <c>using</c> directives.
    /// </summary>
    public IReadOnlyList<string> AdditionalImports { get; init; } = [];

    /// <summary>
    /// Alias imports (for example <c>using Enums = My.Namespace.Enums;</c>)
    /// carried from source files into the script preamble.
    /// </summary>
    public IReadOnlyDictionary<string, string> UsingAliases { get; init; } =
        new Dictionary<string, string>(StringComparer.Ordinal);

    /// <summary>
    /// Static imports (for example <c>using static System.Math;</c>) carried
    /// from source files into the script preamble.
    /// </summary>
    public IReadOnlyList<string> UsingStaticTypes { get; init; } = [];

    /// <summary>
    /// Authoritative local symbol graph extracted by LSP at the expression origin scope.
    /// Daemon uses this graph as the sole source for local variable declaration synthesis.
    /// </summary>
    public IReadOnlyList<LocalSymbolGraphEntry> LocalSymbolGraph { get; init; } = [];

    /// <summary>
    /// When true, generates and invokes an async runner method (<c>RunAsync</c>).
    /// Default is false for compatibility with existing execution flow.
    /// </summary>
    public bool UseAsyncRunner { get; init; } = false;

    /// <summary>
    /// Snapshot of how the LSP resolved the target DbContext at hover time.
    /// Carries both local declared-type hints and factory-derived concrete candidates
    /// so the daemon can validate and disambiguate against the loaded runtime model.
    /// </summary>
    public DbContextResolutionSnapshot? DbContextResolution { get; init; }

    /// <summary>
    /// Complete using context snapshot from LSP extraction: all using directives,
    /// aliases, and static usings from the source file at hover time.
    /// Serialized to avoid re-parsing the file in daemon; enables deterministic
    /// caching across multiple hover requests on the same expression.
    /// </summary>
    public UsingContextSnapshot? UsingContextSnapshot { get; init; }

    /// <summary>
    /// Metadata about the parsed expression: its syntactic type (Invocation, Query, MemberAccess),
    /// the file location where it was extracted, and confidence that it's a valid LINQ query.
    /// Used by daemon for validation and debugging; enables cross-version compatibility checks.
    /// </summary>
    public ParsedExpressionMetadata? ExpressionMetadata { get; init; }

    /// <summary>
    /// Source origin where the final executable expression was extracted from.
    /// For helper extraction this points to helper-method source, not call-site source.
    /// </summary>
    public ExtractionOriginSnapshot? ExtractionOrigin { get; init; }

    /// <summary>
    /// Optional v2 capture plan snapshot generated by LSP.
    /// Slice 2 keeps LocalSymbolGraph as the runtime adapter while carrying the
    /// authoritative capture policy for deterministic diagnostics and migration.
    /// </summary>
    public V2CapturePlanSnapshot? V2CapturePlan { get; init; }

    /// <summary>
    /// Optional v2 extraction plan snapshot generated by LSP.
    /// Carries extraction IR decisions (boundary kind, root context, applied helpers, diagnostics)
    /// so runtime can make deterministic codegen and diagnostic decisions in slice 3+.
    /// </summary>
    public V2QueryExtractionPlanSnapshot? V2ExtractionPlan { get; init; }
}

public static class TranslationRequestContract
{
    public const int Version = 3;
}

/// <summary>
/// Snapshot of DbContext resolution signals observed by the LSP.
/// </summary>
public record DbContextResolutionSnapshot
{
    /// <summary>
    /// Type name declared in source for the hovered context variable.
    /// May be a concrete DbContext, an interface, or a simple name.
    /// </summary>
    public string? DeclaredTypeName { get; init; }

    /// <summary>
    /// Single concrete type derived from QueryLens factory discovery when unambiguous.
    /// </summary>
    public string? FactoryTypeName { get; init; }

    /// <summary>
    /// All concrete DbContext types declared by QueryLens factories in the selected host project.
    /// Populated when more than one factory exists so Core can disambiguate with expression shape.
    /// </summary>
    public IReadOnlyList<string> FactoryCandidateTypeNames { get; init; } = [];

    /// <summary>
    /// Human-readable description of which hint sources contributed to this snapshot.
    /// </summary>
    public string? ResolutionSource { get; init; }

    /// <summary>
    /// LSP confidence that the selected DbContext hint is correct (0.0 to 1.0).
    /// Lower values indicate conflicting or ambiguous hints that should be revalidated in Core.
    /// </summary>
    public double Confidence { get; init; } = 1.0;
}

/// <summary>
/// Complete snapshot of using context extracted by LSP from source file.
/// Enables daemon to cache and skip re-parsing the same file on repeated requests.
/// </summary>
public record UsingContextSnapshot
{
    /// <summary>All regular namespace imports (using X.Y.Z;).</summary>
    public IReadOnlyList<string> Imports { get; init; } = [];

    /// <summary>Namespace aliases (using Alias = X.Y.Z;).</summary>
    public IReadOnlyDictionary<string, string> Aliases { get; init; } =
        new Dictionary<string, string>(StringComparer.Ordinal);

    /// <summary>Static type imports (using static X.Y.Z;).</summary>
    public IReadOnlyList<string> StaticTypes { get; init; } = [];
}

/// <summary>
/// Metadata about the parsed LINQ expression extracted by LSP.
/// Used for validation, caching, and cross-version compatibility.
/// </summary>
public record ParsedExpressionMetadata
{
    /// <summary>
    /// Syntactic expression type: "Invocation" (.ToList()), "Query" (from...select),
    /// or "MemberAccess" (db.Orders). Helps daemon validate expression shape.
    /// </summary>
    public string? ExpressionType { get; init; }

    /// <summary>
    /// Zero-based line number in source file where expression starts. Enables
    /// daemon to validate that expression still exists at same location if file changed.
    /// </summary>
    public int SourceLine { get; init; }

    /// <summary>
    /// Zero-based character offset on SourceLine where expression starts.
    /// </summary>
    public int SourceCharacter { get; init; }

    /// <summary>
    /// LSP's confidence that this is a valid LINQ query chain (0.0 to 1.0).
    /// High confidence = recognized pattern (method chain); low = ambiguous extraction.
    /// Helpful for daemon diagnostics.
    /// </summary>
    public double Confidence { get; init; } = 1.0;
}

/// <summary>
/// Rich symbol hint captured by LSP extraction for a variable visible at hover position.
/// </summary>
public sealed record LocalSymbolHint
{
    public required string Name { get; init; }
    public required string TypeName { get; init; }
    public string Kind { get; init; } = "local";
    public string? InitializerExpression { get; init; }
    public int DeclarationOrder { get; init; }
    public IReadOnlyList<string> Dependencies { get; init; } = [];
    public string? Scope { get; init; }
    public string ReplayPolicy { get; init; } = LocalSymbolReplayPolicies.ReplayInitializer;
}

/// <summary>
/// Deterministic symbol graph node for local/parameter symbols required by extracted expression.
/// </summary>
public sealed record LocalSymbolGraphEntry
{
    public required string Name { get; init; }
    public required string TypeName { get; init; }
    public string Kind { get; init; } = "local";
    public string? InitializerExpression { get; init; }
    public int DeclarationOrder { get; init; }
    public IReadOnlyList<string> Dependencies { get; init; } = [];
    public string? Scope { get; init; }
    public string ReplayPolicy { get; init; } = LocalSymbolReplayPolicies.ReplayInitializer;
}

public static class LocalSymbolReplayPolicies
{
    public const string ReplayInitializer = "ReplayInitializer";
    public const string UsePlaceholder = "UsePlaceholder";
    public const string Reject = "Reject";
}

/// <summary>
/// Canonical hint values used in <see cref="V2CapturePlanEntry.QueryUsageHint"/>.
/// Set by LSP operator-context analysis to select more accurate placeholder defaults.
/// </summary>
public static class QueryUsageHints
{
    /// <summary>Variable is a CancellationToken argument (ToListAsync(ct), etc.). Use CancellationToken.None.</summary>
    public const string CancellationToken = "cancellation-token";

    /// <summary>Variable is used in Skip or Take operator. Positive int is already the canonical default.</summary>
    public const string SkipTake = "skip-take";

    /// <summary>Variable is a LINQ selector Expression&lt;Func&lt;T,R&gt;&gt; argument (.Select(expression)). Generate typed lambda.</summary>
    public const string SelectorExpression = "selector-expression";

    /// <summary>String variable used in Contains(value) predicate. Default "qlstub0" is appropriate.</summary>
    public const string StringContains = "string-contains";

    /// <summary>String variable used in StartsWith(prefix) predicate. Shorter "ql" prefix is more natural.</summary>
    public const string StringPrefix = "string-prefix";

    /// <summary>String variable used in EndsWith(suffix) predicate. Shorter "stub" suffix is more natural.</summary>
    public const string StringSuffix = "string-suffix";

    /// <summary>Variable is used in a Where predicate. Standard catalog default applies.</summary>
    public const string WherePredicate = "where-predicate";

    /// <summary>Variable is a collection used for membership testing (.Contains(x)). Two-item seeding already applied.</summary>
    public const string MembershipCollection = "membership-collection";
}

/// <summary>
/// Deterministic capture-plan snapshot produced by the v2 extraction pipeline.
/// </summary>
public sealed record V2CapturePlanSnapshot
{
    public required string ExecutableExpression { get; init; }
    public IReadOnlyList<V2CapturePlanEntry> Entries { get; init; } = [];
    public IReadOnlyList<V2CaptureDiagnostic> Diagnostics { get; init; } = [];
    public bool IsComplete { get; init; }
}

/// <summary>
/// Individual capture decision emitted by the v2 capture planner.
/// </summary>
public sealed record V2CapturePlanEntry
{
    public required string Name { get; init; }
    public required string TypeName { get; init; }
    public string Kind { get; init; } = "local";
    public string? InitializerExpression { get; init; }
    public int DeclarationOrder { get; init; }
    public IReadOnlyList<string> Dependencies { get; init; } = [];
    public string? Scope { get; init; }
    public string CapturePolicy { get; init; } = LocalSymbolReplayPolicies.UsePlaceholder;
    public string? RejectCode { get; init; }
    public string? RejectReason { get; init; }

    /// <summary>
    /// Optional hint from LSP operator context analysis describing how this variable is used in the query.
    /// Values: "cancellation-token", "skip-take", "selector-expression", "string-contains", "string-prefix",
    ///         "string-suffix", "where-predicate", "membership-collection".
    /// Used by EvalSourceBuilder to select context-aware placeholder values.
    /// </summary>
    public string? QueryUsageHint { get; init; }
}

/// <summary>
/// Structured diagnostic describing why a capture was unresolved or rejected during v2 extraction planning.
/// Implements the full diagnostic schema from docs/unresolved-capture-examples.md.
/// 
/// Diagnostic codes follow the pattern: QLDIAG_{CATEGORY}_{NUMBER}
/// Examples: QLDIAG_CLOSURE_CHAIN_001, QLDIAG_NONDETERMINISTIC_SRC_001, QLDIAG_PLACEHOLDER_UNSUPPORTED_001
/// </summary>
public sealed record V2CaptureDiagnostic
{
    /// <summary>Stable diagnostic code (e.g., "QLDIAG_CLOSURE_CHAIN_001").</summary>
    public required string Code { get; init; }

    /// <summary>Unresolved capture category from docs/unresolved-capture-examples.md:
    /// closure-chain-not-materializable, nondeterministic-source, side-effectful-initializer,
    /// unsupported-expression-form, generic-type-ambiguity, control-flow-dependent-value,
    /// async-state-dependent, reflection-or-dynamic-invocation, cross-assembly-visibility-limit,
    /// translation-semantics-unverifiable, or placeholder-unsupported (for v2 uses-placeholder rejection).
    /// </summary>
    public string Category { get; init; } = "unclassified";

    /// <summary>Captured symbol identifier (e.g., "request", "token", "term").</summary>
    public required string SymbolName { get; init; }

    /// <summary>Full member path when available (e.g., "request.AuthContext.CurrentTenant.Id").</summary>
    public string? SymbolPath { get; init; }

    /// <summary>Short machine-readable reason code (e.g., "unsafe-evaluation-side-effects", "initializer-not-observable").</summary>
    public string Reason { get; init; } = "unknown";

    /// <summary>Human-readable explanation of the unresolved capture.</summary>
    public required string Message { get; init; }

    /// <summary>Optional actionable guidance (e.g., "Consider moving the value to a local variable outside the query").</summary>
    public string? SuggestedFix { get; init; }

    /// <summary>Optional provider context for translation-risk cases (e.g., "SqlServer", "Sqlite", "PostgreSQL").</summary>
    public string? Provider { get; init; }

    /// <summary>Source file location if available (e.g., "CustomerReadService.cs").</summary>
    public string? SourceFile { get; init; }

    /// <summary>Source line number (1-based) if available.</summary>
    public int? SourceLine { get; init; }

    /// <summary>Source character offset (0-based) if available.</summary>
    public int? SourceCharacter { get; init; }
}

/// <summary>
/// Snapshot of v2 extraction plan produced by LSP extraction pipeline.
/// Carries extraction IR decisions for runtime codegen and diagnostics.
/// </summary>
public sealed record V2QueryExtractionPlanSnapshot
{
    /// <summary>The final compiled expression string after extraction/helper-inlining.</summary>
    public required string Expression { get; init; }

    /// <summary>The context variable name (e.g., "dbContext", "db") resolved during extraction.</summary>
    public required string ContextVariableName { get; init; }

    /// <summary>Root context variable traced back to query root (DbSet access, etc.).</summary>
    public required string RootContextVariableName { get; init; }

    /// <summary>First member access after root (e.g., "Users" in "db.Users").</summary>
    public string RootMemberName { get; init; } = string.Empty;

    /// <summary>Call-site expression if extraction involved helper inlining.</summary>
    public string? CallSiteExpression { get; init; }

    /// <summary>Extraction metadata: where the expression was sourced from.</summary>
    public ExtractionOriginSnapshot? Origin { get; init; }

    /// <summary>Boundary kind: whether the extracted expression is materialized (e.g., has ToList) or queryable.</summary>
    public string BoundaryKind { get; init; } = "Queryable"; // "Materialized" or "Queryable"

    /// <summary>Whether the runtime needs to synthesize materialization (e.g., add ToListAsync if missing).</summary>
    public bool NeedsMaterialization { get; init; }

    /// <summary>List of helper method names that were inlined during extraction.</summary>
    public IReadOnlyList<string> AppliedHelperMethods { get; init; } = [];

    /// <summary>Diagnostics from extraction analysis (if any).</summary>
    public IReadOnlyList<V2ExtractionDiagnostic> Diagnostics { get; init; } = [];
}

/// <summary>
/// Diagnostic describing why extraction failed or was constrained in v2 planning.
/// </summary>
public sealed record V2ExtractionDiagnostic
{
    public required string Code { get; init; }
    public required string Message { get; init; }
}

/// <summary>
/// Source location snapshot where executable expression origin was resolved.
/// </summary>
public sealed record ExtractionOriginSnapshot
{
    public string? FilePath { get; init; }
    public int Line { get; init; }
    public int Character { get; init; }
    public int EndLine { get; init; }
    public int EndCharacter { get; init; }
    public string? Scope { get; init; }
}

/// <summary>
/// Type hint for a member access rooted on a local symbol.
/// Example: receiver=minTotal, member=HasValue, type=bool.
/// </summary>
public sealed record MemberTypeHint
{
    public required string ReceiverName { get; init; }
    public required string MemberName { get; init; }
    public required string TypeName { get; init; }
}
