// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Share.Common.Workflow.Api.Client.Workflows.Applications.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Share.Common.Workflow.Api.Client.Workflows.Applications
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\applications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Share.Common.Workflow.Api.Client.workflows.applications.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.WithApplicationItemRequestBuilder"/></returns>
        public global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.WithApplicationItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("applicationId", position);
                return new global::Share.Common.Workflow.Api.Client.Workflows.Applications.Item.WithApplicationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.ApplicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/applications", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Applications.ApplicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/applications", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
