using System.Reflection;
using System.Text;

namespace EFQueryLens.Core.Scripting.DesignTime;

/// <summary>
/// Generates the content of a <c>QueryLensDbContextFactory</c> file for a given
/// DbContext type. The generated file is:
/// <list type="bullet">
///   <item>Wrapped in <c>#if DEBUG</c> — excluded from Release/Staging builds entirely.</item>
///   <item>Marked <c>// &lt;auto-generated by EF QueryLens /&gt;</c> — Roslyn, StyleCop,
///     SonarQube, and most static analysers skip auto-generated files by convention.</item>
///   <item>Bracketed with <c>#pragma warning disable / ReSharper disable All</c> as a
///     belt-and-suspenders guard for analysers that do not respect the header.</item>
///   <item>Uses <c>Name=_querylens</c> as the connection string — resolved by EF Core via
///     <c>IConfiguration.GetConnectionString("_querylens")</c>. QueryLens's offline fake
///     configuration handles this automatically; users may also add a real entry in
///     <c>appsettings.Development.json</c> for their own local use.</item>
/// </list>
/// </summary>
public static class FactoryCodeGenerator
{
    /// <summary>
    /// Generates factory file content for the given DbContext type.
    /// </summary>
    /// <param name="dbContextTypeFullName">
    /// Fully-qualified type name, e.g. <c>"MyApp.Infrastructure.Persistence.AppDbContext"</c>.
    /// </param>
    /// <param name="loadedAssemblies">
    /// Assemblies already loaded into the project ALC — used to detect the EF Core provider.
    /// </param>
    /// <returns>C# source code for the factory file.</returns>
    public static string Generate(
        string dbContextTypeFullName,
        IEnumerable<Assembly> loadedAssemblies)
    {
        var parts = dbContextTypeFullName.Split('.');
        var simpleTypeName = parts.Last();
        var ns = string.Join(".", parts.SkipLast(1));
        var providerCall = DetectProviderCall(loadedAssemblies);
        var factoryClassName = $"{simpleTypeName}QueryLensFactory";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by EF QueryLens />");
        sb.AppendLine("// Development-only file for offline SQL preview. Excluded from Release builds.");
        sb.AppendLine("// Safe to commit — no real database connection is ever opened.");
        sb.AppendLine("// The Name=_querylens connection string is handled automatically by QueryLens.");
        sb.AppendLine("// You can also add a real entry in appsettings.Development.json for local use.");
        sb.AppendLine("#if DEBUG");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("// ReSharper disable All");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {factoryClassName}");
            sb.AppendLine($"        : EFQueryLens.Core.IQueryLensDbContextFactory<{simpleTypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {simpleTypeName} CreateOfflineContext()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var options = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<{simpleTypeName}>()");
            sb.AppendLine($"                {providerCall}");
            sb.AppendLine("                .Options;");
            sb.AppendLine($"            return new {simpleTypeName}(options);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        else
        {
            // Global namespace (rare but valid)
            sb.AppendLine($"public sealed class {factoryClassName}");
            sb.AppendLine($"    : EFQueryLens.Core.IQueryLensDbContextFactory<{simpleTypeName}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public {simpleTypeName} CreateOfflineContext()");
            sb.AppendLine("    {");
            sb.AppendLine($"        var options = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<{simpleTypeName}>()");
            sb.AppendLine($"            {providerCall}");
            sb.AppendLine("            .Options;");
            sb.AppendLine($"        return new {simpleTypeName}(options);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        sb.AppendLine("#pragma warning restore");
        sb.AppendLine("// ReSharper restore All");
        sb.Append("#endif");

        return sb.ToString();
    }

    /// <summary>
    /// Suggests a file name for the generated factory, e.g.
    /// <c>"AppDbContextQueryLensFactory.cs"</c>.
    /// </summary>
    public static string SuggestFileName(string dbContextTypeFullName)
    {
        var simpleTypeName = dbContextTypeFullName.Split('.').Last();
        return $"{simpleTypeName}QueryLensFactory.cs";
    }

    private static string DetectProviderCall(IEnumerable<Assembly> assemblies)
    {
        var names = assemblies
            .Select(a => a.GetName().Name ?? string.Empty)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        if (names.Any(n => n.Contains("SqlServer", StringComparison.OrdinalIgnoreCase)
                        && n.Contains("EntityFrameworkCore", StringComparison.OrdinalIgnoreCase)))
            return ".UseSqlServer(\"Name=_querylens\")";

        if (names.Any(n => n.Contains("Pomelo", StringComparison.OrdinalIgnoreCase)))
            return ".UseMySql(\"Name=_querylens\", new MySqlServerVersion(new Version(8, 0, 0)))";

        if (names.Any(n => n.Contains("Npgsql", StringComparison.OrdinalIgnoreCase)
                        && n.Contains("EntityFrameworkCore", StringComparison.OrdinalIgnoreCase)))
            return ".UseNpgsql(\"Name=_querylens\")";

        if (names.Any(n => n.Contains("Sqlite", StringComparison.OrdinalIgnoreCase)
                        && n.Contains("EntityFrameworkCore", StringComparison.OrdinalIgnoreCase)))
            return ".UseSqlite(\"Data Source=:memory:\")";

        // Unknown provider — emit a placeholder the user can fill in
        return "// TODO: .UseSqlServer(\"Name=_querylens\") or .UseNpgsql(...) / .UseMySql(...) etc.";
    }
}
