using EFQueryLens.Core.Scaffolding;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace EFQueryLens.Core.Tests.Scaffolding;

public sealed class FactoryRendererTests
{
    private static readonly string[] OneContext = ["SampleApp.AppDbContext"];
    private static readonly string[] TwoContexts = ["SampleApp.AppDbContext", "SampleApp.ReportingDbContext"];

    [Fact]
    public void Render_AlwaysHasAutoGeneratedHeaderAndHash()
    {
        var content = FactoryRenderer.Render(ProviderKind.SqlServer, useProjectables: false, useSplitQuery: true, OneContext);

        Assert.StartsWith("// <auto-generated/>", content, StringComparison.Ordinal);
        Assert.Contains(FactoryRenderer.HashMarker, content, StringComparison.Ordinal);
        Assert.Contains("namespace EFQueryLens.Core", content, StringComparison.Ordinal);
        Assert.Contains("interface IQueryLensDbContextFactory", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Render_SqlServer_UsesProviderAndOfflineConnectionAndSplit()
    {
        var content = FactoryRenderer.Render(ProviderKind.SqlServer, useProjectables: true, useSplitQuery: true, OneContext);

        Assert.Contains(".UseSqlServer(", content, StringComparison.Ordinal);
        Assert.Contains("ef_querylens_offline", content, StringComparison.Ordinal);
        Assert.Contains("TrustServerCertificate=True", content, StringComparison.Ordinal);
        Assert.Contains("UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)", content, StringComparison.Ordinal);
        Assert.Contains(".UseProjectables()", content, StringComparison.Ordinal);
        AssertCompiles(content);
    }

    [Fact]
    public void Render_MySql_UsesFixedServerVersion_NotAutoDetect()
    {
        var content = FactoryRenderer.Render(ProviderKind.MySql, useProjectables: true, useSplitQuery: true, OneContext);

        Assert.Contains(".UseMySql(", content, StringComparison.Ordinal);
        Assert.Contains("new MySqlServerVersion(new System.Version(8, 0, 36))", content, StringComparison.Ordinal);
        Assert.DoesNotContain("AutoDetect", content, StringComparison.Ordinal);
        AssertCompiles(content);
    }

    [Fact]
    public void Render_Npgsql_UsesNpgsql()
    {
        var content = FactoryRenderer.Render(ProviderKind.Npgsql, useProjectables: false, useSplitQuery: true, OneContext);

        Assert.Contains(".UseNpgsql(", content, StringComparison.Ordinal);
        Assert.Contains("Host=ef_querylens_offline", content, StringComparison.Ordinal);
        AssertCompiles(content);
    }

    [Fact]
    public void Render_Sqlite_NoProjectablesNoSplitInMemory()
    {
        var content = FactoryRenderer.Render(ProviderKind.Sqlite, useProjectables: true, useSplitQuery: true, OneContext);

        Assert.Contains(".UseSqlite(\"Data Source=:memory:\")", content, StringComparison.Ordinal);
        Assert.DoesNotContain(".UseProjectables()", content, StringComparison.Ordinal);
        Assert.DoesNotContain("UseQuerySplittingBehavior", content, StringComparison.Ordinal);
        AssertCompiles(content);
    }

    [Fact]
    public void Render_OneFactoryClassPerContext()
    {
        var content = FactoryRenderer.Render(ProviderKind.SqlServer, useProjectables: false, useSplitQuery: true, TwoContexts);

        Assert.Contains("AppDbContextQueryLensFactory", content, StringComparison.Ordinal);
        Assert.Contains("ReportingDbContextQueryLensFactory", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Render_UsesReflectiveQueryLensDbContextActivator()
    {
        var content = FactoryRenderer.Render(ProviderKind.SqlServer, useProjectables: false, useSplitQuery: true, OneContext);

        Assert.Contains("internal static class QueryLensDbContextActivator", content, StringComparison.Ordinal);
        Assert.Contains("return QueryLensDbContextActivator.Create<", content, StringComparison.Ordinal);
        Assert.DoesNotContain("return new SampleApp.AppDbContext(options);", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Render_EmitsQueryLensDbContextActivatorAfterFactoryClasses()
    {
        var content = FactoryRenderer.Render(ProviderKind.SqlServer, useProjectables: false, useSplitQuery: true, TwoContexts);

        var appFactoryIndex = content.IndexOf("AppDbContextQueryLensFactory", StringComparison.Ordinal);
        var reportingFactoryIndex = content.IndexOf("ReportingDbContextQueryLensFactory", StringComparison.Ordinal);
        var activatorIndex = content.IndexOf("internal static class QueryLensDbContextActivator", StringComparison.Ordinal);

        Assert.True(appFactoryIndex >= 0);
        Assert.True(reportingFactoryIndex > appFactoryIndex);
        Assert.True(activatorIndex > reportingFactoryIndex);
    }

    [Fact]
    public void Render_WithExactChain_UsesProvidedOptionsChain()
    {
        var plans = new[]
        {
            new ContextRenderPlan
            {
                ContextFullName = "SampleApp.AppDbContext",
                Provider = ProviderKind.MySql,
                UseProjectables = true,
                UseSplitQuery = true,
                OfflineOptionsChain =
                    ".UseMySql(\"Server=ef_querylens_offline;Database=ef_querylens_offline\", new MySqlServerVersion(new Version(8, 0, 36)), mySql => mySql.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)).UseProjectables()",
                ExtraUsings = ["EntityFrameworkCore.Projectables", "Microsoft.EntityFrameworkCore"],
            },
        };

        var content = FactoryRenderer.Render(plans);

        Assert.Contains("new MySqlServerVersion(new Version(8, 0, 36))", content, StringComparison.Ordinal);
        Assert.Contains(".UseProjectables()", content, StringComparison.Ordinal);
        Assert.DoesNotContain("new System.Version(8, 0, 36)", content, StringComparison.Ordinal);
        AssertCompiles(content);
    }

    [Fact]
    public void Render_IsDeterministic_SameInputsSameOutput()
    {
        var a = FactoryRenderer.Render(ProviderKind.SqlServer, true, true, TwoContexts);
        var b = FactoryRenderer.Render(ProviderKind.SqlServer, true, true, TwoContexts);

        Assert.Equal(a, b);
    }

    [Fact]
    public void Render_RecordedHash_MatchesBodyHash()
    {
        var content = FactoryRenderer.Render(ProviderKind.Npgsql, false, true, OneContext);

        Assert.True(FactoryRenderer.TryReadRecordedHash(content, out var recorded, out var body));
        Assert.Equal(FactoryRenderer.ComputeHash(body), recorded);
    }

    // Syntax-level compile check: the generated source must be well-formed C#.
    // (Full semantic compilation needs the provider assemblies; reflection discovery and the
    // integration test prove it builds + runs against a real sample.)
    private static void AssertCompiles(string content)
    {
        var tree = CSharpSyntaxTree.ParseText(content);
        var errors = tree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.True(errors.Count == 0, "Generated source has syntax errors: " + string.Join("; ", errors.Select(e => e.GetMessage())));
    }
}
