using EFQueryLens.Core.AssemblyContext;
using EFQueryLens.Core.Scaffolding;
using EFQueryLens.Core.Tests.Scripting;

namespace EFQueryLens.Core.Tests.Scaffolding;

/// <summary>
/// Exercises the scaffolder against a real built sample assembly (DbContext discovery + provider
/// detection are real) while writing the generated factory into a throwaway temp project dir.
/// Shares the ALC-isolation collection so it doesn't run concurrently with other assembly loads.
/// </summary>
[Collection("QueryEvaluatorIsolation")]
public sealed class FactoryScaffolderTests : IDisposable
{
    private readonly string _projectDir = Path.Combine(Path.GetTempPath(), $"ql-scaffold-{Guid.NewGuid():N}");

    public FactoryScaffolderTests() => Directory.CreateDirectory(_projectDir);

    private static string SampleDll => QueryEvaluatorTests.GetSampleMySqlAppDll();

    private static string SampleMySqlProjectDir =>
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "samples", "SampleMySqlApp"));

    private SetupRequest Request(bool force = false, string? projectDirectory = null) => new()
    {
        AssemblyPath = SampleDll,
        ProjectDirectory = projectDirectory ?? _projectDir,
        Force = force,
    };

    private string GeneratedPath(string projectDirectory) =>
        Path.Combine(new[] { projectDirectory }.Concat(FactoryScaffolder.GeneratedRelativePath).ToArray());

    [Fact]
    public void Run_DiscoverContextsViaShadowBundle()
    {
        var shadowRoot = Path.Combine(Path.GetTempPath(), $"ql-scaffold-shadow-{Guid.NewGuid():N}");
        Directory.CreateDirectory(shadowRoot);
        var prevShadowRoot = Environment.GetEnvironmentVariable("QUERYLENS_SHADOW_ROOT");
        Environment.SetEnvironmentVariable("QUERYLENS_SHADOW_ROOT", shadowRoot);

        try
        {
            ShadowAssemblyContextLoader.ResetSharedCacheForTests();
            var result = FactoryScaffolder.Run(Request());

            Assert.Equal(SetupAction.Generated, result.Action);
            using var ctx = ShadowAssemblyContextLoader.Create(SampleDll);
            Assert.StartsWith(shadowRoot, ctx.AssemblyPath, StringComparison.OrdinalIgnoreCase);
            Assert.True(Directory.Exists(Path.Combine(shadowRoot, "bundles")));
        }
        finally
        {
            Environment.SetEnvironmentVariable(
                "QUERYLENS_SHADOW_ROOT",
                string.IsNullOrEmpty(prevShadowRoot) ? null : prevShadowRoot);
            try { Directory.Delete(shadowRoot, recursive: true); } catch { /* best-effort */ }
        }
    }

    [Fact]
    public void Run_NotBuilt_WhenAssemblyMissing()
    {
        var result = FactoryScaffolder.Run(new SetupRequest
        {
            AssemblyPath = Path.Combine(_projectDir, "does-not-exist.dll"),
            ProjectDirectory = _projectDir,
        });

        Assert.Equal(SetupAction.NotBuilt, result.Action);
    }

    [Fact]
    public void Run_GeneratesFactory_DetectsProviderAndContexts_AndUpdatesGitignore()
    {
        var result = FactoryScaffolder.Run(Request());

        Assert.Equal(SetupAction.Generated, result.Action);
        Assert.Equal(ProviderKind.MySql, result.Provider);
        Assert.True(result.RequiresReview);
        Assert.True(result.UsedBestEffortDefaults);
        Assert.Contains(result.Contexts, c => c.EndsWith("MySqlAppDbContext", StringComparison.Ordinal));
        Assert.True(File.Exists(GeneratedPath(_projectDir)));

        var content = File.ReadAllText(GeneratedPath(_projectDir));
        Assert.StartsWith("// <auto-generated/>", content, StringComparison.Ordinal);
        Assert.Contains("PLEASE REVIEW", content, StringComparison.Ordinal);
        Assert.Contains("Please review Properties/QueryLens", result.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("best-effort defaults", result.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(".UseMySql(", content, StringComparison.Ordinal);

        var gitignore = File.ReadAllText(Path.Combine(_projectDir, ".gitignore"));
        Assert.Contains(FactoryScaffolder.GitignoreRule, gitignore, StringComparison.Ordinal);
    }

    [Fact]
    public void Run_WithSampleMySqlProjectDir_UsesExactRegistrationChain()
    {
        var projectDir = SampleMySqlProjectDir;
        var generatedPath = GeneratedPath(projectDir);
        var handWrittenFactory = Path.Combine(projectDir, "QueryLensDbContextFactory.cs");
        var factoryBackup = handWrittenFactory + ".ql-test-bak";
        var generatedExisted = File.Exists(generatedPath);
        var generatedBackup = generatedPath + ".ql-test-bak";
        var gitignorePath = Path.Combine(projectDir, ".gitignore");
        var gitignoreExisted = File.Exists(gitignorePath);
        var gitignoreBackup = gitignorePath + ".ql-test-bak";

        if (File.Exists(handWrittenFactory))
        {
            File.Move(handWrittenFactory, factoryBackup, overwrite: true);
        }

        if (generatedExisted)
        {
            File.Move(generatedPath, generatedBackup, overwrite: true);
        }

        if (gitignoreExisted)
        {
            File.Move(gitignorePath, gitignoreBackup, overwrite: true);
        }

        try
        {
            var result = FactoryScaffolder.Run(Request(projectDirectory: projectDir));

            Assert.Equal(SetupAction.Generated, result.Action);
            Assert.True(result.RequiresReview);
            Assert.Contains(
                result.ContextsNeedingReview,
                name => name.EndsWith("MySqlReportingDbContext", StringComparison.Ordinal));
            var content = File.ReadAllText(generatedPath);
            Assert.Contains("PLEASE REVIEW", content, StringComparison.Ordinal);
            Assert.Contains("Please review Properties/QueryLens", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.True(result.UsedBestEffortDefaults);
            Assert.Contains("best-effort defaults", result.Message, StringComparison.OrdinalIgnoreCase);
            var appFactoryStart = content.IndexOf("MySqlAppDbContextQueryLensFactory", StringComparison.Ordinal);
            var reportingFactoryStart = content.IndexOf("MySqlReportingDbContextQueryLensFactory", StringComparison.Ordinal);
            Assert.True(appFactoryStart >= 0);
            Assert.True(reportingFactoryStart > appFactoryStart);

            var appFactorySection = content[appFactoryStart..reportingFactoryStart];
            Assert.Contains("new MySqlServerVersion(new Version(8, 0, 36))", appFactorySection, StringComparison.Ordinal);
            Assert.Contains("UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)", appFactorySection, StringComparison.Ordinal);
            Assert.Contains(".UseProjectables()", appFactorySection, StringComparison.Ordinal);
            Assert.Contains("QueryLensDbContextActivator.Create<", appFactorySection, StringComparison.Ordinal);
            Assert.DoesNotContain("new System.Version(8, 0, 36)", appFactorySection, StringComparison.Ordinal);
        }
        finally
        {
            if (File.Exists(generatedPath))
            {
                File.Delete(generatedPath);
            }

            if (generatedExisted && File.Exists(generatedBackup))
            {
                File.Move(generatedBackup, generatedPath, overwrite: true);
            }

            if (File.Exists(gitignorePath))
            {
                File.Delete(gitignorePath);
            }

            if (gitignoreExisted && File.Exists(gitignoreBackup))
            {
                File.Move(gitignoreBackup, gitignorePath, overwrite: true);
            }

            if (File.Exists(factoryBackup))
            {
                File.Move(factoryBackup, handWrittenFactory, overwrite: true);
            }
        }
    }

    [Fact]
    public void Run_Twice_SecondIsUpToDate_NoChange()
    {
        FactoryScaffolder.Run(Request());
        var first = File.ReadAllText(GeneratedPath(_projectDir));

        var second = FactoryScaffolder.Run(Request());

        Assert.Equal(SetupAction.SkippedUpToDate, second.Action);
        Assert.Equal(first, File.ReadAllText(GeneratedPath(_projectDir)));
    }

    [Fact]
    public void Run_RefusesToOverwriteHandEditedFile_UnlessForced()
    {
        FactoryScaffolder.Run(Request());
        File.AppendAllText(GeneratedPath(_projectDir), "\n// hand edit\n");

        var refused = FactoryScaffolder.Run(Request());
        Assert.Equal(SetupAction.RefusedEdited, refused.Action);

        var forced = FactoryScaffolder.Run(Request(force: true));
        Assert.Equal(SetupAction.Generated, forced.Action);
        Assert.DoesNotContain("// hand edit", File.ReadAllText(GeneratedPath(_projectDir)), StringComparison.Ordinal);
    }

    [Fact]
    public void Run_SkipsWhenHandWrittenFactoryAlreadyExists()
    {
        File.WriteAllText(
            Path.Combine(_projectDir, "MyFactory.cs"),
            "class X : EFQueryLens.Core.IQueryLensDbContextFactory<object> { }");

        var result = FactoryScaffolder.Run(Request());

        Assert.Equal(SetupAction.SkippedExistingFactory, result.Action);
        Assert.False(File.Exists(GeneratedPath(_projectDir)));
    }

    public void Dispose()
    {
        try { Directory.Delete(_projectDir, recursive: true); } catch { /* best-effort */ }
    }
}
