using System.Security.Cryptography;
using System.Text;

namespace EFQueryLens.Core.Scaffolding;

/// <summary>
/// Renders the offline <c>IQueryLensDbContextFactory&lt;T&gt;</c> factory source for a project.
/// </summary>
public static class FactoryRenderer
{
    public const string HashMarker = "// querylens-setup-hash: ";
    private const string TemplateVersion = "v2";

    public static string Render(
        ProviderKind provider,
        bool useProjectables,
        bool useSplitQuery,
        IReadOnlyList<string> contextFullNames)
    {
        var plans = contextFullNames
            .Select(name => new ContextRenderPlan
            {
                ContextFullName = name,
                Provider = provider,
                UseProjectables = useProjectables,
                UseSplitQuery = useSplitQuery,
                OfflineOptionsChain = null,
                ExtraUsings = [],
            })
            .ToList();

        return Render(plans);
    }

    public static string Render(IReadOnlyList<ContextRenderPlan> contexts)
    {
        var body = RenderBody(contexts);
        var hash = ComputeHash(body);

        var sb = new StringBuilder();
        AppendGeneratedHeader(sb, contexts);
        sb.Append(HashMarker).Append(hash).Append(' ').Append(TemplateVersion).Append('\n');
        sb.Append(body);
        return sb.ToString();
    }

    /// <summary>SHA256 (first 16 hex chars) of the rendered body — embedded in the header.</summary>
    public static string ComputeHash(string body)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(NormalizeNewlines(body)));
        return Convert.ToHexString(bytes)[..16].ToLowerInvariant();
    }

    public static bool TryReadRecordedHash(string fileContent, out string recordedHash, out string body)
    {
        recordedHash = string.Empty;
        body = string.Empty;

        var markerIndex = fileContent.IndexOf(HashMarker, StringComparison.Ordinal);
        if (markerIndex < 0)
        {
            return false;
        }

        var afterMarker = fileContent[(markerIndex + HashMarker.Length)..];
        var newlineIndex = afterMarker.IndexOf('\n');
        if (newlineIndex < 0)
        {
            return false;
        }

        recordedHash = afterMarker[..newlineIndex].Trim().Split(' ')[0];
        body = afterMarker[(newlineIndex + 1)..];
        return true;
    }

    public static string NormalizeNewlines(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");

    internal static void AppendGeneratedHeader(StringBuilder sb, IReadOnlyList<ContextRenderPlan> contexts)
    {
        sb.Append("// <auto-generated/>\n");
        sb.Append("// EF QueryLens — generated factory for offline SQL preview. Do not edit;\n");
        sb.Append("// re-run \"Set up QueryLens\" to regenerate. This file is git-ignored.\n");
        sb.Append("// Connection strings are offline placeholders; SQL preview never connects to a database.\n");
        sb.Append("//\n");
        sb.Append("// PLEASE REVIEW: Compare each CreateOfflineContext() below with your AddDbContext\n");
        sb.Append("// configuration and add any missing EF options your app relies on (for example\n");
        sb.Append("// UseProjectables, split queries, or provider-specific settings).\n");

        if (contexts.Any(static plan => !plan.MatchedRegistration))
        {
            sb.Append("// Note: one or more DbContexts below used detected defaults because no matching\n");
            sb.Append("// AddDbContext registration was found in source.\n");
        }
    }

    private static string RenderBody(IReadOnlyList<ContextRenderPlan> contexts)
    {
        var usings = CollectUsings(contexts);

        var sb = new StringBuilder();
        sb.Append("#nullable disable\n");
        foreach (var usingDirective in usings)
        {
            sb.Append("using ").Append(usingDirective).Append(";\n");
        }

        sb.Append('\n');
        sb.Append("// ReSharper disable once CheckNamespace\n");
        sb.Append("namespace EFQueryLens.Core\n{\n");
        sb.Append("    internal interface IQueryLensDbContextFactory<out TContext>\n");
        sb.Append("        where TContext : DbContext\n");
        sb.Append("    {\n");
        sb.Append("        TContext CreateOfflineContext();\n");
        sb.Append("    }\n");
        sb.Append("}\n\n");

        sb.Append("namespace EFQueryLens.Generated\n{\n");

        for (var i = 0; i < contexts.Count; i++)
        {
            if (i > 0)
            {
                sb.Append('\n');
            }

            AppendFactoryClass(sb, contexts[i]);
        }

        if (contexts.Count > 0)
        {
            sb.Append('\n');
        }

        AppendQueryLensDbContextActivator(sb);

        sb.Append("}\n");
        return sb.ToString();
    }

    private static IReadOnlyList<string> CollectUsings(IReadOnlyList<ContextRenderPlan> contexts)
    {
        var usings = new HashSet<string>(StringComparer.Ordinal)
        {
            "Microsoft.EntityFrameworkCore",
            "System",
        };

        foreach (var context in contexts)
        {
            foreach (var extraUsing in context.ExtraUsings)
            {
                usings.Add(extraUsing);
            }

            if (context.UseProjectables && context.Provider != ProviderKind.Sqlite)
            {
                usings.Add("EntityFrameworkCore.Projectables");
            }
        }

        return usings.OrderBy(static u => u, StringComparer.Ordinal).ToList();
    }

    private static void AppendQueryLensDbContextActivator(StringBuilder sb)
    {
        sb.Append("    internal static class QueryLensDbContextActivator\n");
        sb.Append("    {\n");
        sb.Append("        public static TContext Create<TContext>(DbContextOptions<TContext> options)\n");
        sb.Append("            where TContext : DbContext\n");
        sb.Append("        {\n");
        sb.Append("            var type = typeof(TContext);\n");
        sb.Append("            foreach (var ctor in type.GetConstructors())\n");
        sb.Append("            {\n");
        sb.Append("                var parameters = ctor.GetParameters();\n");
        sb.Append("                if (parameters.Length == 0)\n");
        sb.Append("                {\n");
        sb.Append("                    continue;\n");
        sb.Append("                }\n");
        sb.Append("\n");
        sb.Append("                var args = new object[parameters.Length];\n");
        sb.Append("                var hasOptions = false;\n");
        sb.Append("                for (var i = 0; i < parameters.Length; i++)\n");
        sb.Append("                {\n");
        sb.Append("                    var parameterType = parameters[i].ParameterType;\n");
        sb.Append("                    if (!hasOptions && (parameterType == typeof(DbContextOptions)\n");
        sb.Append("                        || (parameterType.IsGenericType\n");
        sb.Append("                            && parameterType.GetGenericTypeDefinition() == typeof(DbContextOptions<>))))\n");
        sb.Append("                    {\n");
        sb.Append("                        args[i] = options;\n");
        sb.Append("                        hasOptions = true;\n");
        sb.Append("                        continue;\n");
        sb.Append("                    }\n");
        sb.Append("\n");
        sb.Append("                    args[i] = parameterType.IsValueType\n");
        sb.Append("                        ? Activator.CreateInstance(parameterType)\n");
        sb.Append("                        : null;\n");
        sb.Append("                }\n");
        sb.Append("\n");
        sb.Append("                if (hasOptions)\n");
        sb.Append("                {\n");
        sb.Append("                    return (TContext)ctor.Invoke(args);\n");
        sb.Append("                }\n");
        sb.Append("            }\n");
        sb.Append("\n");
        sb.Append("            throw new InvalidOperationException(\n");
        sb.Append("                $\"No suitable constructor found for {type.FullName}. \"\n");
        sb.Append("                + \"Expected a constructor whose first DbContextOptions parameter can be supplied offline.\");\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
    }

    private static void AppendFactoryClass(StringBuilder sb, ContextRenderPlan plan)
    {
        var className = SimpleName(plan.ContextFullName) + "QueryLensFactory";
        var ctx = "global::" + plan.ContextFullName;

        sb.Append("    internal sealed class ").Append(className).Append('\n');
        sb.Append("        : EFQueryLens.Core.IQueryLensDbContextFactory<").Append(ctx).Append(">\n");
        sb.Append("    {\n");
        sb.Append("        public ").Append(ctx).Append(" CreateOfflineContext()\n");
        sb.Append("        {\n");
        sb.Append("            var options = new DbContextOptionsBuilder<").Append(ctx).Append(">()\n");

        if (!string.IsNullOrWhiteSpace(plan.OfflineOptionsChain))
        {
            var chain = plan.OfflineOptionsChain.Trim();
            if (!chain.StartsWith(".", StringComparison.Ordinal))
            {
                chain = "." + chain;
            }

            sb.Append("                ").Append(chain).Append('\n');
        }
        else
        {
            sb.Append("                ").Append(TemplateProviderConfig(plan.Provider, plan.UseSplitQuery)).Append('\n');
            if (plan.UseProjectables && plan.Provider != ProviderKind.Sqlite)
            {
                sb.Append("                .UseProjectables()\n");
            }
        }

        sb.Append("                .Options;\n");
        sb.Append("            return QueryLensDbContextActivator.Create<").Append(ctx).Append(">(options);\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
    }

    private static string TemplateProviderConfig(ProviderKind provider, bool useSplitQuery)
    {
        var split = useSplitQuery
            ? ", o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)"
            : string.Empty;

        return provider switch
        {
            ProviderKind.SqlServer =>
                $".UseSqlServer(\"Server=ef_querylens_offline;Database=ef_querylens_offline;User Id=ef_querylens_offline;Password=ef_querylens_offline;TrustServerCertificate=True\"{split})",
            ProviderKind.Npgsql =>
                $".UseNpgsql(\"Host=ef_querylens_offline;Database=ef_querylens_offline;Username=ef_querylens_offline;Password=ef_querylens_offline\"{split})",
            ProviderKind.MySql =>
                $".UseMySql(\"Server=ef_querylens_offline;Database=ef_querylens_offline;User Id=ef_querylens_offline;Password=ef_querylens_offline\", new MySqlServerVersion(new System.Version(8, 0, 36)){split})",
            ProviderKind.Sqlite =>
                ".UseSqlite(\"Data Source=:memory:\")",
            _ => throw new ArgumentOutOfRangeException(nameof(provider), provider, "Provider must be resolved before rendering."),
        };
    }

    private static string SimpleName(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        var name = lastDot >= 0 ? fullName[(lastDot + 1)..] : fullName;
        var plus = name.LastIndexOf('+');
        return plus >= 0 ? name[(plus + 1)..] : name;
    }
}
