// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EFQueryLens.VisualStudio2
{
    internal sealed partial class Vsix
    {
        public const string Id = "EFQueryLens.VisualStudio2.a7bbfd8d-70d2-4a85-8aba-855260a74897";
        public const string Name = "EFQueryLens.VisualStudio2";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
