// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Share.Common.Workflow.Api.Client.Models;
using Share.Common.Workflow.Api.Client.Workflows.Item.Applications;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Share.Common.Workflow.Api.Client.Workflows.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\{workflowType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithWorkflowTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applications property</summary>
        public global::Share.Common.Workflow.Api.Client.Workflows.Item.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Share.Common.Workflow.Api.Client.Workflows.Item.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/{workflowType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/{workflowType}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 500 status code</exception>
        /// <exception cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse">When receiving a 502 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "404", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "500", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
                { "502", global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse>(requestInfo, global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Share.Common.Workflow.Api.Client.Workflows.Item.WithWorkflowTypeItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
