// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AssignWorkflowStageRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assigneerAccountId property</summary>
        public Guid? AssigneerAccountId { get; set; }
        /// <summary>The assingeeAccountId property</summary>
        public Guid? AssingeeAccountId { get; set; }
        /// <summary>The level property</summary>
        public int? Level { get; set; }
        /// <summary>The remarks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>The stage property</summary>
        public int? Stage { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.AssignWorkflowStageRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.AssignWorkflowStageRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.AssignWorkflowStageRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigneerAccountId", n => { AssigneerAccountId = n.GetGuidValue(); } },
                { "assingeeAccountId", n => { AssingeeAccountId = n.GetGuidValue(); } },
                { "level", n => { Level = n.GetIntValue(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
                { "stage", n => { Stage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("assigneerAccountId", AssigneerAccountId);
            writer.WriteGuidValue("assingeeAccountId", AssingeeAccountId);
            writer.WriteIntValue("level", Level);
            writer.WriteStringValue("remarks", Remarks);
            writer.WriteIntValue("stage", Stage);
        }
    }
}
#pragma warning restore CS0618
