// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseEndpointResponse : ApiException, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The errorMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse_BaseValidationError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse_BaseValidationError> Errors { get; set; }
#endif
        /// <summary>The isSuccess property</summary>
        public bool? IsSuccess { get; set; }
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse_BaseValidationError>(global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse_BaseValidationError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isSuccess", n => { IsSuccess = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteCollectionOfObjectValues<global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse_BaseValidationError>("errors", Errors);
            writer.WriteBoolValue("isSuccess", IsSuccess);
        }
    }
}
#pragma warning restore CS0618
