// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DealerLicenseNew")]
        #pragma warning disable CS1591
        DealerLicenseNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseRenewal")]
        #pragma warning disable CS1591
        DealerLicenseRenewal,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseAmendment")]
        #pragma warning disable CS1591
        DealerLicenseAmendment,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseCancellation")]
        #pragma warning disable CS1591
        DealerLicenseCancellation,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseFullfilmentOfApprovalCondition")]
        #pragma warning disable CS1591
        DealerLicenseFullfilmentOfApprovalCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseApprovalConditionChange")]
        #pragma warning disable CS1591
        DealerLicenseApprovalConditionChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseStatusChange")]
        #pragma warning disable CS1591
        DealerLicenseStatusChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseFoacExtension")]
        #pragma warning disable CS1591
        DealerLicenseFoacExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationNewImmediate")]
        #pragma warning disable CS1591
        ProductRegistrationNewImmediate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationRenewal")]
        #pragma warning disable CS1591
        ProductRegistrationRenewal,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationAmendment")]
        #pragma warning disable CS1591
        ProductRegistrationAmendment,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationNewExpedited")]
        #pragma warning disable CS1591
        ProductRegistrationNewExpedited,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationFullfilmentOfApprovalCondition")]
        #pragma warning disable CS1591
        ProductRegistrationFullfilmentOfApprovalCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationApprovalConditionChange")]
        #pragma warning disable CS1591
        ProductRegistrationApprovalConditionChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationStatusChange")]
        #pragma warning disable CS1591
        ProductRegistrationStatusChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationFoacExtension")]
        #pragma warning disable CS1591
        ProductRegistrationFoacExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "ChangeOfRegistrantNew")]
        #pragma warning disable CS1591
        ChangeOfRegistrantNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "ChangeNotificationNewAdministrativeOrNotificationSmdr")]
        #pragma warning disable CS1591
        ChangeNotificationNewAdministrativeOrNotificationSmdr,
        #pragma warning restore CS1591
        [EnumMember(Value = "ChangeNotificationNewTechnicalOrReview")]
        #pragma warning disable CS1591
        ChangeNotificationNewTechnicalOrReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpecialAccessRouteNew")]
        #pragma warning disable CS1591
        SpecialAccessRouteNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpecialAccessRouteFullfilmentOfApprovalCondition")]
        #pragma warning disable CS1591
        SpecialAccessRouteFullfilmentOfApprovalCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpecialAccessRouteApprovalConditionChange")]
        #pragma warning disable CS1591
        SpecialAccessRouteApprovalConditionChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpecialAccessRouteDistributionRecord")]
        #pragma warning disable CS1591
        SpecialAccessRouteDistributionRecord,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpecialAccessRouteFoacExtension")]
        #pragma warning disable CS1591
        SpecialAccessRouteFoacExtension,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExportCertificateNew")]
        #pragma warning disable CS1591
        ExportCertificateNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "FreeSaleCertificateNew")]
        #pragma warning disable CS1591
        FreeSaleCertificateNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductNotificationStatusChange")]
        #pragma warning disable CS1591
        ProductNotificationStatusChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "ImporterTaggingNew")]
        #pragma warning disable CS1591
        ImporterTaggingNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "AppointmentBookingNew")]
        #pragma warning disable CS1591
        AppointmentBookingNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductNotificationNew")]
        #pragma warning disable CS1591
        ProductNotificationNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductNotificationAmendment")]
        #pragma warning disable CS1591
        ProductNotificationAmendment,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerNotificationNew")]
        #pragma warning disable CS1591
        DealerNotificationNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerNotificationAmendment")]
        #pragma warning disable CS1591
        DealerNotificationAmendment,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationNew")]
        #pragma warning disable CS1591
        ProductRegistrationNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationMajorVariation")]
        #pragma warning disable CS1591
        ProductRegistrationMajorVariation,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationMinorVariation")]
        #pragma warning disable CS1591
        ProductRegistrationMinorVariation,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationChangeOfRegistrant")]
        #pragma warning disable CS1591
        ProductRegistrationChangeOfRegistrant,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationDeva")]
        #pragma warning disable CS1591
        ProductRegistrationDeva,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationRmp")]
        #pragma warning disable CS1591
        ProductRegistrationRmp,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationFulfilment")]
        #pragma warning disable CS1591
        ProductRegistrationFulfilment,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductRegistrationRetention")]
        #pragma warning disable CS1591
        ProductRegistrationRetention,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseNewImporterWholesalerLicense")]
        #pragma warning disable CS1591
        DealerLicenseNewImporterWholesalerLicense,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenceUpdateImporterWholesalerLicence")]
        #pragma warning disable CS1591
        DealerLicenceUpdateImporterWholesalerLicence,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseNewManufacturerLicense")]
        #pragma warning disable CS1591
        DealerLicenseNewManufacturerLicense,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenceUpdateManufacturerLicence")]
        #pragma warning disable CS1591
        DealerLicenceUpdateManufacturerLicence,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseCancelImporterWholesalerLicense")]
        #pragma warning disable CS1591
        DealerLicenseCancelImporterWholesalerLicense,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerLicenseCancelManufacturerLicense")]
        #pragma warning disable CS1591
        DealerLicenseCancelManufacturerLicense,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerCertificateNewGDP")]
        #pragma warning disable CS1591
        DealerCertificateNewGDP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerCertificateNewGDPWithoutTechnicalAssessment")]
        #pragma warning disable CS1591
        DealerCertificateNewGDPWithoutTechnicalAssessment,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerCertificateNewGMP")]
        #pragma warning disable CS1591
        DealerCertificateNewGMP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DealerCertificateNewGMPWithoutTechnicalAssessment")]
        #pragma warning disable CS1591
        DealerCertificateNewGMPWithoutTechnicalAssessment,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuditCaseILWL")]
        #pragma warning disable CS1591
        AuditCaseILWL,
        #pragma warning restore CS1591
        [EnumMember(Value = "AuditCaseML")]
        #pragma warning disable CS1591
        AuditCaseML,
        #pragma warning restore CS1591
        [EnumMember(Value = "PharmaceuticalProductNew")]
        #pragma warning disable CS1591
        PharmaceuticalProductNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "FreeSaleNew")]
        #pragma warning disable CS1591
        FreeSaleNew,
        #pragma warning restore CS1591
    }
}
