// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowPrivilegeType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RaiseIr")]
        #pragma warning disable CS1591
        RaiseIr,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreateChildCase")]
        #pragma warning disable CS1591
        CreateChildCase,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReviewDealerActivities")]
        #pragma warning disable CS1591
        ReviewDealerActivities,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReviewProducts")]
        #pragma warning disable CS1591
        ReviewProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "Approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "Reject")]
        #pragma warning disable CS1591
        Reject,
        #pragma warning restore CS1591
        [EnumMember(Value = "InitiateDeferredPayment")]
        #pragma warning disable CS1591
        InitiateDeferredPayment,
        #pragma warning restore CS1591
        [EnumMember(Value = "RaiseQuery")]
        #pragma warning disable CS1591
        RaiseQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExtendIr")]
        #pragma warning disable CS1591
        ExtendIr,
        #pragma warning restore CS1591
        [EnumMember(Value = "InstantApprove")]
        #pragma warning disable CS1591
        InstantApprove,
        #pragma warning restore CS1591
        [EnumMember(Value = "InstantReject")]
        #pragma warning disable CS1591
        InstantReject,
        #pragma warning restore CS1591
        [EnumMember(Value = "GrantThirdPartyIrAccess")]
        #pragma warning disable CS1591
        GrantThirdPartyIrAccess,
        #pragma warning restore CS1591
    }
}
