// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowPrivilegeRequirementType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RequiredToCompleteStage")]
        #pragma warning disable CS1591
        RequiredToCompleteStage,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequiredIfInitiated")]
        #pragma warning disable CS1591
        RequiredIfInitiated,
        #pragma warning restore CS1591
        [EnumMember(Value = "Optional")]
        #pragma warning disable CS1591
        Optional,
        #pragma warning restore CS1591
    }
}
