// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowStageIdentifier
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Verification")]
        #pragma warning disable CS1591
        Verification,
        #pragma warning restore CS1591
        [EnumMember(Value = "AcceptForEvaluation")]
        #pragma warning disable CS1591
        AcceptForEvaluation,
        #pragma warning restore CS1591
        [EnumMember(Value = "Evaluation")]
        #pragma warning disable CS1591
        Evaluation,
        #pragma warning restore CS1591
        [EnumMember(Value = "Support")]
        #pragma warning disable CS1591
        Support,
        #pragma warning restore CS1591
        [EnumMember(Value = "Approval")]
        #pragma warning disable CS1591
        Approval,
        #pragma warning restore CS1591
    }
}
