// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AssignmentOfficer")]
        #pragma warning disable CS1591
        AssignmentOfficer,
        #pragma warning restore CS1591
        [EnumMember(Value = "VerificationOfficer")]
        #pragma warning disable CS1591
        VerificationOfficer,
        #pragma warning restore CS1591
        [EnumMember(Value = "EvaluationOfficer")]
        #pragma warning disable CS1591
        EvaluationOfficer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SupportingOfficer")]
        #pragma warning disable CS1591
        SupportingOfficer,
        #pragma warning restore CS1591
        [EnumMember(Value = "ApprovingOfficer")]
        #pragma warning disable CS1591
        ApprovingOfficer,
        #pragma warning restore CS1591
    }
}
