// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Enums_WorkflowDecision
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Reject")]
        #pragma warning disable CS1591
        Reject,
        #pragma warning restore CS1591
        [EnumMember(Value = "Approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "ReturnForAmendment")]
        #pragma warning disable CS1591
        ReturnForAmendment,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnTag")]
        #pragma warning disable CS1591
        UnTag,
        #pragma warning restore CS1591
        [EnumMember(Value = "Assign")]
        #pragma warning disable CS1591
        Assign,
        #pragma warning restore CS1591
        [EnumMember(Value = "InstantApprove")]
        #pragma warning disable CS1591
        InstantApprove,
        #pragma warning restore CS1591
        [EnumMember(Value = "InstantReject")]
        #pragma warning disable CS1591
        InstantReject,
        #pragma warning restore CS1591
    }
}
