// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetApplicationWorkflowResponse_ApplicationWorkflowStageItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The canAssignToMe property</summary>
        public bool? CanAssignToMe { get; set; }
        /// <summary>The canReject property</summary>
        public bool? CanReject { get; set; }
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The decision property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision? Decision { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The stageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageId { get; set; }
#nullable restore
#else
        public string StageId { get; set; }
#endif
        /// <summary>The stageIdentifier property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowStageIdentifier? StageIdentifier { get; set; }
        /// <summary>The stageName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageName { get; set; }
#nullable restore
#else
        public string StageName { get; set; }
#endif
        /// <summary>The startedAt property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The supportingOfficer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupportingOfficer { get; set; }
#nullable restore
#else
        public string SupportingOfficer { get; set; }
#endif
        /// <summary>The supportingOfficerId property</summary>
        public Guid? SupportingOfficerId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.GetApplicationWorkflowResponse_ApplicationWorkflowStageItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.GetApplicationWorkflowResponse_ApplicationWorkflowStageItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.GetApplicationWorkflowResponse_ApplicationWorkflowStageItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canAssignToMe", n => { CanAssignToMe = n.GetBoolValue(); } },
                { "canReject", n => { CanReject = n.GetBoolValue(); } },
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "decision", n => { Decision = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision>(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "stageId", n => { StageId = n.GetStringValue(); } },
                { "stageIdentifier", n => { StageIdentifier = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowStageIdentifier>(); } },
                { "stageName", n => { StageName = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "supportingOfficer", n => { SupportingOfficer = n.GetStringValue(); } },
                { "supportingOfficerId", n => { SupportingOfficerId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("canAssignToMe", CanAssignToMe);
            writer.WriteBoolValue("canReject", CanReject);
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision>("decision", Decision);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteStringValue("stageId", StageId);
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowStageIdentifier>("stageIdentifier", StageIdentifier);
            writer.WriteStringValue("stageName", StageName);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteStringValue("supportingOfficer", SupportingOfficer);
            writer.WriteGuidValue("supportingOfficerId", SupportingOfficerId);
        }
    }
}
#pragma warning restore CS0618
