// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetWorkflowByTypeResponse : global::Share.Common.Workflow.Api.Client.Models.BaseEndpointResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The workflow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Share.Common.Workflow.Api.Client.Models.WorkflowResponse? Workflow { get; set; }
#nullable restore
#else
        public global::Share.Common.Workflow.Api.Client.Models.WorkflowResponse Workflow { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.GetWorkflowByTypeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "workflow", n => { Workflow = n.GetObjectValue<global::Share.Common.Workflow.Api.Client.Models.WorkflowResponse>(global::Share.Common.Workflow.Api.Client.Models.WorkflowResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Share.Common.Workflow.Api.Client.Models.WorkflowResponse>("workflow", Workflow);
        }
    }
}
#pragma warning restore CS0618
