// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostWorkflowStageDecisionRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public Guid? AccountId { get; set; }
        /// <summary>The decision property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision? Decision { get; set; }
        /// <summary>The decisionDate property</summary>
        public DateTimeOffset? DecisionDate { get; set; }
        /// <summary>The isFinalStage property</summary>
        public bool? IsFinalStage { get; set; }
        /// <summary>The nextLevel property</summary>
        public int? NextLevel { get; set; }
        /// <summary>The nextStage property</summary>
        public int? NextStage { get; set; }
        /// <summary>The remarks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.PostWorkflowStageDecisionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.PostWorkflowStageDecisionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.PostWorkflowStageDecisionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetGuidValue(); } },
                { "decision", n => { Decision = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision>(); } },
                { "decisionDate", n => { DecisionDate = n.GetDateTimeOffsetValue(); } },
                { "isFinalStage", n => { IsFinalStage = n.GetBoolValue(); } },
                { "nextLevel", n => { NextLevel = n.GetIntValue(); } },
                { "nextStage", n => { NextStage = n.GetIntValue(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("accountId", AccountId);
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowDecision>("decision", Decision);
            writer.WriteDateTimeOffsetValue("decisionDate", DecisionDate);
            writer.WriteBoolValue("isFinalStage", IsFinalStage);
            writer.WriteIntValue("nextLevel", NextLevel);
            writer.WriteIntValue("nextStage", NextStage);
            writer.WriteStringValue("remarks", Remarks);
        }
    }
}
#pragma warning restore CS0618
