// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowLevelStagePrivilegeResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The privilegeRequirementType property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeRequirementType? PrivilegeRequirementType { get; set; }
        /// <summary>The privilegeType property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeType? PrivilegeType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStagePrivilegeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStagePrivilegeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStagePrivilegeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "privilegeRequirementType", n => { PrivilegeRequirementType = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeRequirementType>(); } },
                { "privilegeType", n => { PrivilegeType = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeRequirementType>("privilegeRequirementType", PrivilegeRequirementType);
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowPrivilegeType>("privilegeType", PrivilegeType);
        }
    }
}
#pragma warning restore CS0618
