// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Share.Common.Workflow.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowLevelResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The isFinal property</summary>
        public bool? IsFinal { get; set; }
        /// <summary>The level property</summary>
        public int? Level { get; set; }
        /// <summary>The stages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStageResponse>? Stages { get; set; }
#nullable restore
#else
        public List<global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStageResponse> Stages { get; set; }
#endif
        /// <summary>The workflowRole property</summary>
        public global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowRole? WorkflowRole { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isFinal", n => { IsFinal = n.GetBoolValue(); } },
                { "level", n => { Level = n.GetIntValue(); } },
                { "stages", n => { Stages = n.GetCollectionOfObjectValues<global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStageResponse>(global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStageResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "workflowRole", n => { WorkflowRole = n.GetEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowRole>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isFinal", IsFinal);
            writer.WriteIntValue("level", Level);
            writer.WriteCollectionOfObjectValues<global::Share.Common.Workflow.Api.Client.Models.WorkflowLevelStageResponse>("stages", Stages);
            writer.WriteEnumValue<global::Share.Common.Workflow.Api.Client.Models.Enums_WorkflowRole>("workflowRole", WorkflowRole);
        }
    }
}
#pragma warning restore CS0618
